/*Users*/
SELECT USERNAME, ACCOUNT_STATUS, EXPIRY_DATE, CREATED,
        USER_ID, DEFAULT_TABLESPACE
FROM DBA_USERS;

/*ROLES*/
SELECT ROLE, ROLE_ID, AUTHENTICATION_TYPE, COMMON
FROM DBA_ROLES;

/*Grants*/
SELECT ROLE, GRANTED_ROLE
FROM ROLE_ROLE_PRIVS;

/*Tablespace*/
SELECT TBS.TABLESPACE_NAME,USG.USED_SPACE,USG.USED_PERCENT,TBS.MAX_SIZE,TBS.STATUS,TBS.CONTENTS,DF.FILE_NAME,DF.AUTOEXTENSIBLE,
(TABLESPACE_SIZE - USED_SPACE) AS FREE_SPACE
FROM DBA_TABLESPACE_USAGE_METRICS  USG, DBA_TABLESPACES  TBS, DBA_DATA_FILES  DF
WHERE TBS.TABLESPACE_NAME = USG.TABLESPACE_NAME AND TBS.TABLESPACE_NAME = DF.TABLESPACE_NAME;

/*DataFiles*/
SELECT FILE_NAME, FILE_ID, TABLESPACE_NAME, BYTES, STATUS, AUTOEXTENSIBLE,
USER_BYTES
FROM DBA_DATA_FILES;

/*Sessions*/
SELECT SECONDS_IN_WAIT
FROM V_$SESSION;

SELECT
   s.username,
   t.sid,
   s.serial#,
   s.seconds_in_wait,
   SUM(VALUE/100) as "cpu usage (seconds)"
FROM
   v$session s,
   v$sesstat t,
   v$statname n
WHERE
   t.STATISTIC# = n.STATISTIC#
AND
   NAME like '%CPU used by this session%'
AND
   t.SID = s.SID
AND
   s.status='ACTIVE'
AND
   s.username is not null
GROUP BY username,t.sid,s.serial#,s.seconds_in_wait;

/*Memory*/
SELECT
    s.name as SGA_NAME,
    s.value as SGA_VALUE,
    p.pga_max_mem as DATA_STORAGE,
    p.pname as PGA
FROM 
    v$sga s,
    v$process p;
