 CREATE VIEW tab_dataFiles AS
    SELECT T.NAME_TABLESPACE,T.TYPE_TABLESPACE,T.FREE_SPACE,D.NAME_DATAFILE, D.AUTOEXTENSIBLE, D.STATUS
        FROM TABLESPACE_T T
    INNER JOIN DATAFILE_T D
    ON T.NAME_TABLESPACE = D.NAME_TABLESPACE
    ORDER BY T.FREE_SPACE DESC;
  
CREATE VIEW mem_hist AS
    SELECT M.*
    FROM MEMORY_HISTORY M
    ORDER BY M.TIME_STAMP DESC;

CREATE VIEW dataFile_hist AS
    SELECT D.*
    FROM DATAFILE_HISTORY D
    ORDER BY D.TIME_STAMP DESC;

CREATE VIEW sessions_hist AS
    SELECT D.*
    FROM SESSIONS_HISTORY D
    ORDER BY D.TIME_STAMP DESC;

CREATE VIEW tablespace_hist AS
    SELECT D.*
    FROM TABLESPACE_HISTORY D
    ORDER BY D.TIME_STAMP DESC;

CREATE VIEW user_hist AS
    SELECT D.*
    FROM USER_HISTORY D
    ORDER BY D.TIME_STAMP DESC;
    
CREATE VIEW user_openStatus AS
    SELECT U.*
    FROM USER_T U
    WHERE U.STATUS = 'OPEN';
    
CREATE VIEW user_roles_tablespaces AS
    SELECT DISTINCT U.USERNAME, T.NAME_TABLESPACE, listagg(R.NAME_ROLE,',') WITHIN GROUP (ORDER BY U.USERNAME, T.NAME_TABLESPACE) AS ROLES_NAMES
    FROM USER_T U
    INNER JOIN USER_HAS_ROLE UHR
    ON U.USER_ID = UHR.USER_ID
    INNER JOIN ROLE_T R
    ON UHR.ROLE_ID = R.ROLE_ID
    INNER JOIN TABLESPACE_USER TU
    ON TU.USER_ID = U.USER_ID
    INNER JOIN TABLESPACE_T T
    ON TU.NAME_TABLESPACE = T.NAME_TABLESPACE
    GROUP BY U.USERNAME, T.NAME_TABLESPACE
    ORDER BY U.USERNAME;
