CREATE VIEW mem_view AS
SELECT * from MEMORY_HISTORY
ORDER BY TIME_STAMP DESC;

CREATE VIEW user_role_view AS
SELECT USERNAME, NAME_ROLE
FROM USER_T U, ROLE_T R, USER_HAS_ROLE UHR
WHERE U.USER_ID = UHR.USER_ID AND R.ROLE_ID = UHR.ROLE_ID;

CREATE VIEW user_tabl_view AS
SELECT T.NAME_TABLESPACE, USERNAME
FROM USER_T U, TABLESPACE_T T, TABLESPACE_USER TU
WHERE TU.USER_ID = U.USER_ID AND TU.NAME_TABLESPACE = T.NAME_TABLESPACE;

CREATE VIEW session_view AS
SELECT WAIT_SESSIONS
FROM SESSIONS_HISTORY;